Imports y configuración

In [ ]:
import sys
from pathlib import Path
 
CWD       = Path().resolve()
PROJ_ROOT = Path(r"C:\Users\jorge gonzalez\Documents\TFG\Proyecto")
 
if str(PROJ_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJ_ROOT))
 
from src.utils    import ensure_dir
from src.assemble import make_hotel_ttoo_datasets
 
import pandas as pd
import glob
 
print("Project root:", PROJ_ROOT)

Project root: C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean

Rutas

In [6]:
HOTEL_PARQUET = PROJ_ROOT / "data" / "processed" / "livvo_day_hotel_final.parquet"
TTOO_PARQUET  = PROJ_ROOT / "data" / "processed" / "livvo_day_ttoo_final.parquet"
OUT_DIR       = PROJ_ROOT / "data" / "features" / "hotel_ttoo"
 
ensure_dir(OUT_DIR)
 
print("Hotel parquet:", HOTEL_PARQUET)
print("TTOO parquet: ", TTOO_PARQUET)
print("Output dir:   ", OUT_DIR)

Hotel parquet: C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean\data\processed\livvo_day_hotel_final.parquet
TTOO parquet:  C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean\data\processed\livvo_day_ttoo_final.parquet
Output dir:    C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean\data\features\hotel_ttoo

Generación de datasets

In [7]:
make_hotel_ttoo_datasets(
    HOTEL_PARQUET,
    TTOO_PARQUET,
    OUT_DIR,
)
print("Datasets por hotel con features de canales generados.")

Datasets por hotel con features de canales generados.

C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean\src\features_ttoo.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["fecha", "hotel", "ttoo"])["roomnights"]
C:\Users\jorge gonzalez\Documents\TFG\Proyecto_clean\src\features_ttoo.py:17: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  wide = agg.pivot_table(

Sanity check

In [8]:
paths = glob.glob(str(OUT_DIR / "*.parquet"))
print("Parquets generados:", paths)
 
for p in paths:
    df      = pd.read_parquet(p)
    rn_cols = [c for c in df.columns if c.startswith("rn_")]
 
    print(f"\n📁 {Path(p).name}")
    print("shape:", df.shape)
    print("nº cols de canal:", len(rn_cols))
 
    required = {"fecha", "hotel", "ocup_total", "is_weekend", "season"}
    faltan   = required - set(df.columns)
 
    if faltan:
        print("❌ Faltan columnas:", faltan)
    else:
        print("✅ Base hotel OK")
 
    display(df[["fecha", "hotel", "ocup_total"] + rn_cols[:5]].head(3))

Parquets generados: ['C:\\Users\\jorge gonzalez\\Documents\\TFG\\Proyecto_clean\\data\\features\\hotel_ttoo\\HOTEL_1.parquet', 'C:\\Users\\jorge gonzalez\\Documents\\TFG\\Proyecto_clean\\data\\features\\hotel_ttoo\\HOTEL_2.parquet', 'C:\\Users\\jorge gonzalez\\Documents\\TFG\\Proyecto_clean\\data\\features\\hotel_ttoo\\HOTEL_3.parquet']

📁 HOTEL_1.parquet
shape: (1024, 21)
nº cols de canal: 16
✅ Base hotel OK

       fecha    hotel  ocup_total  rn_AL  rn_AV  rn_B  rn_C  rn_EA
0 2023-01-01  HOTEL_1    0.510638    0.0    0.0  19.0   0.0    0.0
1 2023-01-02  HOTEL_1    0.659574    0.0    0.0  26.0   0.0    0.0
2 2023-01-03  HOTEL_1    0.627660    0.0    0.0  24.0   0.0    0.0

📁 HOTEL_2.parquet
shape: (929, 21)
nº cols de canal: 16
✅ Base hotel OK

       fecha    hotel  ocup_total  rn_AL  rn_AV  rn_B  rn_C  rn_EA
0 2023-01-01  HOTEL_2    0.811594    0.0    0.0  16.0   0.0    0.0
1 2023-01-02  HOTEL_2    0.826087    0.0    0.0  22.0   0.0    0.0
2 2023-01-03  HOTEL_2    0.782609    0.0    0.0  24.0   0.0    0.0

📁 HOTEL_3.parquet
shape: (1085, 21)
nº cols de canal: 16
✅ Base hotel OK

       fecha    hotel  ocup_total  rn_AL  rn_AV  rn_B  rn_C  rn_EA
0 2023-01-01  HOTEL_3    0.613546    4.0   27.0  11.0   0.0    0.0
1 2023-01-02  HOTEL_3    0.653386    4.0   29.0  12.0   0.0    0.0
2 2023-01-03  HOTEL_3    0.633466    2.0   26.0  11.0   0.0    0.0